add first draft of 2023 program
supercontainers/canopie-hpc pull request #12
Opened 2023-10-04 20:40 UTC by lastephey

Adding first draft of CANOPIE-SC23 program

2023-10-04 20:51 UTC, lastephey commented
Rendered version 

![Screenshot 2023-10-04 at 1 50 51 PM](https://github.com/supercontainers/canopie-hpc/assets/6232308/7e4b855f-41e8-41cb-99b8-ade9af02f36e)

2023-10-05 10:36 UTC, Madeeks requested changes

2023-10-05 10:36 UTC, Madeeks commented on docs/program.md
> +        <td>CANOPIE-HPC- Introduction and welcome</td>
```suggestion
        <td>CANOPIE-HPC - Introduction and welcome</td>
```

2023-10-05 10:36 UTC, Madeeks approved these changes

2023-10-05 17:41 UTC, merged

2023-10-05 18:08 UTC, lastephey commented
Thanks @Madeeks! The filesystem where I had this repo crashed, so I was waiting for it to recover. Thanks for making the change!